RELEASENOTES.md, doc/index.md, plugin.xml, src/android/ContentFilesystem.java, src/android/FileUtils.java, src/android/Filesystem.java, src/android/LocalFilesystem.java, src/windows/FileProxy.js, tests/plugin.xml, tests/tests.js, www/Entry.js, www/requestFileSystem.js, www/resolveLocalFileSystemURI.js
CB-7883: toURL method called on etnries returned by resolveLocalFileSystemURL and getDirectory produces path instead of URL. 
This rework produce url's in normal form. The code passes all automated tests, although some tests were massaged for windows platform.
=> Rework to use normal url form on windows platform

src/wp/File.cs, tests/tests.js
Jira issue: https://issues.apache.org/jira/browse/CB-8792
=> CB-8792 Fixes reading of json files using readAsText

src/windows/FileProxy.js, tests/tests.js
write operation of FileWriter overwrites completely contents of existing file after write position was set by seek function. Automated tests for plugin only verify the length of writer object, but do not check the actual data written to file.
Changes included for code and tests.
=> CB-8728 fix write after seek on windows

README.md, package.json, plugin.xml, src/android/FileUtils.java
**TL;DR Summary**
We should switch the default for the Cordova Android File System to be on internal storage, not the SD Card (or emulated SD card).
**Long Version**
Currently in Cordova Android when you use this code "window.requestFileSystem(PERSISTENT, 0, win, fail);" the root file system path that is returned is "/storage/emulated/0" i.e. "/sdcard".
Why you may ask? Because back in 2010 or so Bryce Curtis and I argued that we should use the external storage location because internal storage was not very large on Android 2.x and we didn't want to have developers filling up the devices limited internal storage. Joe Bowser argued against it because of issues with the SD Card on Android but was eventually out voted.
Now, I'm prepared to admit that Bryce was wrong (see what I did there?). …
=> Make Android default persistent file location internal

src/windows/FileProxy.js
readAsText on windows uses Windows.Security.Cryptography.CryptographicBuffer.convertBinaryToString to convert buffer to requested exception. When such conversion can not be made, it throws exception, that is currently not handled. The function shall fail with FileError.ENCODING_ERR instead.
=> CB-9763: added handling for encoding exception in readAsText on Windows

plugin.xml
I'm shooting in the dark, here, so someone knowledgable please check this.
I was previously getting this error:
Failed to install 'cordova-plugin-file':Error: Uh oh!
".../plugins/cordova-plugin-file/src/android/FileHelper.java" not found!
Inspection showed src/android/FileHelper.java doesn't exist, so I removed that line.
I also added the AssetFilesystem.java line for consistency with the android section, but don't know if it's needed.
=> fix install on amazon-fireos

src/ios/CDVAssetLibraryFilesystem.m, src/ios/CDVFile.m, src/ios/CDVLocalFilesystem.m
Encountered memory issues with a non-ARC project (cordova+unity3d). Setter should be used to prevent memory issues, eg:
A synthesized retained setter looks like :
```
- (void)setValue: (id)newValue
{
if (value != newValue)
{
[value release];
value = newValue;
[value retain];
}
} 
```
---
https://issues.apache.org/jira/browse/CB-8669
=> fix(ios): always use setters to fix memory issues without ARC

src/android/AssetFilesystem.java, tests/tests.js
Calls to FileEntry.getDirectory() on an asset entry would internally call
the AssetFileSystem.listAssets() method using an asset path with a
trailing slash, regardless of whether a trailing slash was included by
the user. But neither the asset list cache (from cdvasset.manifest) nor
Android's AssetManager.list() API support matching a path with a trailing
slash. That resulted in a TypeMismatchException thrown from
AssetFileSystem.getFileForLocalURL(), because the asset path was found
but not matched as a directory as expected by the caller.
This fix removes the trailing slash from the asset path before matching
against the asset list cache or calling Android's AssetManager.list() API.
A new unit test for getting asset directories fails without and passes
with the fix.
While I'm here, I'm …
=> Fix CB-9752: FileEntry.getDirectory fails with assets filesystem

src/android/DirectoryManager.java, src/android/FileUtils.java, src/android/Filesystem.java, src/android/LocalFilesystem.java, tests/tests.js
There were 2 issues behind this bug:
1) DirectoryManager.getFreeDiskSpace() used an incorrect way of
checking the free internal storage space: using a path of "/" would
always result in 0 reported free space.
2) When checking whether requested space was available, the
requestFileSystem() method would always check the external storage
space and fallback to internal storage space, regardless of what
type of filesystem (external, internal, or other) was being requested.
To fix both of these issues, I've added a new getFreeSpaceInBytes() method
on the FileSystem base class, which is called on the actual filesystem
instance being retrieved by requestFileSystem(). The new method for
getting free space always uses the filesystem's correct root path, so
it works for internal, external or any …
=> CB-7253: requestFileSystem fails when no external storage is present

README.md, plugin.xml, src/windows/FileProxy.js
Update the plugin to define cordova.file.* paths for windows platform as appropriate.
Documentation updated to show where to store things.
Have tested this in my own app and the paths are detected as file plugin works as expected now.
Means you can use cordova.file.dataDirectory in your app and then run that app on ios, android, windows with consistent behaviour without requiring platform specific code.
=> CB-9887 cordova.file.* paths for windows platform

src/windows/FileProxy.js, tests/tests.js, www/FileSystem.js, www/android/FileSystem.js, www/blackberry10/FileSystem.js, www/blackberry10/createEntryFromNative.js, www/browser/FileSystem.js, www/firefoxos/FileSystem.js, www/ios/FileSystem.js, www/osx/FileSystem.js, www/ubuntu/FileSystem.js
Because # is a valid filename character, it must be encoded whenever it
is in a path that is part of a URI, to prevent part of the path from
being parsed as a URI fragment.
=> CB-8497 Fix handling of file paths with # character

plugin.xml, src/browser/FileProxy.js, www/browser/Preparing.js, www/browser/isChrome.js, www/requestFileSystem.js, www/resolveLocalFileSystemURI.js
We shouldn't be patching `requestFileSystem` and `resolveLocalFileSystem` on Chrome. Recent change broke the existing logic for this.
Also, added common logic for detecting Chrome (or really, feature detection) so we are checking in a consistent manner.
=> CB-10023 Fix "proxy not found error" on Chrome.

www/FileEntry.js
The FileEntry constructor should remove any trailing slash from its path. This parallels the existing DirectoryEntry constructor code which adds a trailing slash if missing.
This is actually not a Windows-specific fix, but it fixes a file plugin test case failure that was observed on Windows after I recently added that test case to validate an Android fix. Windows already invokes the correct FileEntry/DirEntry constructor based on the actual file/directory status of the path, so fixing the trailing slash is all that is needed.
@riknoll or @rakatyal please review
=> CB-10577: Windows resolveLocalFileSystemURL should omit trailing slash for file

tests/src/android/TestContentProvider.java
Seems like `FileDescriptor.toString()` changed in Android N and it broke three of our tests. This removes our dependency on the output of that. Tested on N and Marshmallow.
=> CB-11115 android: Fixing test content provider

src/ios/CDVFile.h
iOS
Fixes iOS embedded webview projects based on the [phonegap-webview-ios template](https://github.com/phonegap/phonegap-webview-ios/) due to the reasons explained in [CB-11407](https://issues.apache.org/jira/browse/CB-11407) and template [issue 8] (https://github.com/phonegap/phonegap-webview-ios/issues/8).
This change has been tested locally with iOS embedded webview projects based on [this template](https://github.com/phonegap/phonegap-webview-ios).
=> CB-11407 (ios): Added extern keyword to constants to fix phonegap-webview-ios template projects

README.md, plugin.xml, src/android/AssetFilesystem.java, src/android/FileUtils.java, tests/tests.js
Android
* Added test for cdvfile applicationDirectory fs root
* Updated the docs and added the assets to Android available fs roots list
* Allow cdvfile: access for android automatically
Jasmine auto and manual tests, app tests (see [Jira](https://issues.apache.org/jira/browse/CB-11305))
=> CB-11305 Enable cdvfile: assets fs root for DOM requests

tests/tests.js, www/FileReader.js
Android, iOS, Windows
This PR fixes reading files as data URLs by modifying chunk size, so concatenated chunks would be a valid Data URL
Ran plugin tests on all affected platforms
When reading file as Data URL, CHUNK_SIZE must be divisible by 3, otherwise the resultant string, made by concatenating chunks, will not be a valid Base64 encoded Data URL. Also Windows do not support reading sliced files as data URLs, so we need to set chunk size equal to file size.
Relevant JIRA issues: [CB-11699](https://issues.apache.org/jira/browse/CB-11699), [CB-11199](https://issues.apache.org/jira/browse/CB-11199)
=> CB-11699 Read files as Data URLs properly

src/ios/CDVLocalFilesystem.m
iOS
fix iOS FileEntry.file callback return a null type
install to project and install on real device (iPhone 5, 6, 6s) and simulator
=> CB-12355: (iOS) fix FileEntry.file.type

.travis.yml, tests/tests.js
Browser
Enables Travis to run tests on browser platform (except chrome)
Chrome blocks test execution by showing a permissions pop-up
See Travis results under this PR
=> CB-13028 (CI) Browser builds on Travis

src/android/FileUtils.java
Android 6+
Allow reading from `cordova.file.applicationDirectory` (`file:///android_asset/`) without asking the user for permission.
Modified the code and ran it on an Android 6.0 device (See sample code in the JIRA bug).
=> CB-13481: (android) Don't ask for permission to read file:///android_asset/

www/fileSystems-roots.js
fix error :
Error in Success callbackId: File1539060614 : TypeError: Cannot read property 'filesystemName' of null
cordova.js:314 Uncaught TypeError: Cannot read property 'filesystemName' of null
The `fsRoot` might be null. reproduced with latest cordova on android emulator.
https://issues.apache.org/jira/browse/CB-14181
=> CB-14181: (android) Fix bug - Cannot read property 'filesystemName' of null

www/FileWriter.js
FileWriter is missing the require('./FileReader') module causing the
native FileReader to be used instead of the FileReader proxy.
Oddly this does not happen everytime, but I could consistently
reproduce the issue when running subsequent `cordova run android`
commands on an Ionic app running in a 7.1.1 Android Emulator.
All Platforms
Witnessed on Android
Adds a missing require statement to ensure the correct FileReader is used
Since this issue was very difficult to reproduce it was pretty hard to test. We found
that this issue occurs most frequently when running our ionic app in the Android
emulator and then run `ionic cordova run android` multiple times to reinstall the app
before we consistently saw the issue. With the changes from this PR we stopped
seeing the issue entirely.
I believe …
=> CB-14197: (all) Fix for createFile/writeFile silently failing to send 'write' action

types/index.d.ts
[This]( https://github.com/apache/cordova-plugin-file/pull/224) was sent by an user, but they closed it because the title was not fine and never resubmitted.
I've checked that it works without the change because it takes the JavaScript value, but changed the value in the .ts for consistency.
Fix inverted LocalFileSystem enum
=> CB-13569: fix inverted LocalFileSystem enum

src/browser/FileProxy.js
cordova-browser 
Bascially cordova-browser uses indexeddb in order to store File(Blob) object as file-saving.
However the private browsing mode on safari browser in mac does not permit to store
File(Blob) object into the indexeddb.
(See Webkit source code https://github.com/WebKit/webkit/blob/5dada1bf8d706e1c544f1a23bfb67f3eaeb4f412/Source/WebCore/Modules/indexeddb/IDBObjectStore.cpp#L328-L331 )
This PR is to fix this issue.
The private borwsing mode on safari throws `DataCloneError` when storing Blob object to indexeddb.
Therefore this PR detects `DataCloneError` and store base64 encoded text instead of Blob object itself.
According to this, decoding/encoding helper functions are introduced.
Note that the safari browser (emulator ?) in the saucelab used in travis ci seems to work in …
=> (browser) support safari private browsing mode by using base64 text instead of blob

plugin.xml
Android
Required when targeting API 29, which is the default target API on `cordova-android@9`. This is a fork of a broken PR https://github.com/apache/cordova-plugin-file/pull/410
Closes #410 
Fixes #408 
Required for https://github.com/apache/cordova-plugin-media-capture/issues/103
Adds `requestLegacyExternalStorage` flag to `AndroidManifest.xml`
Tested against https://github.com/apache/cordova-plugin-media-capture/pull/192#pullrequestreview-487221746
=> fix(android): Use legacy storage

.travis.yml
Android
Make test use API / Build Tools 29.
Fixes some build errors in travis.
Updates Travis
=> test: (android) use API 29

src/android/LocalFilesystem.java
Android
Removes a copied/pasted function in accordance to it's TODO. The pasted `copyResource` function appeared to be a stopgap measure to address a bug that appeared pre cordova-android@4. The note said to remove the function and bring the required `cordova-android` engine to >= 4.0.0
The plugin currently requires `cordova-android` >= 6.3.0 so no changes there was required.
Deleted local copy of `copyResource` and replaced usages with `CordovaResourceApi` version.
ran `npm test` and manually used `copyTo` api.
=> refactor: Removed obsolete copyResource function

package.json, plugin.xml, tests/plugin.xml
all
A change was introduced that forces new requirements, thus a major version bump is necessary.
The offending change is located at: https://github.com/apache/cordova-plugin-file/pull/417 which is required to use file directories outside of the app's private data directory.
This relates to https://github.com/apache/cordova-plugin-file/issues/424 but doesn't resolve it. I'll be creating another PR shortly to complete the resolution.
Bump version numbers.
N/A
=> chore: bump version to 7.0.0-dev

www/browser/Preparing.js
=> fix(browser): typo in preparing.js

.eslintrc.yml, package-lock.json, package.json, src/browser/FileProxy.js, src/windows/FileProxy.js, tests/tests.js, www/DirectoryEntry.js, www/Entry.js, www/FileReader.js, www/FileWriter.js, www/browser/Preparing.js, www/resolveLocalFileSystemURI.js
All
Previous eslint install was not compatible with Node 14.
Progresses https://github.com/apache/cordova/issues/142
Progresses (but does not complete) https://github.com/apache/cordova/issues/223
Removed local eslint install in favour of the shared eslint provided by `@cordova/eslint-config`
Ran `npm test`
=> refactor: shared eslint config

README.md
The section on the file object was missing words.
=> docs: adds missing words to the file object section in the README

src/android/FileUtils.java
Android
Fixes #421 
Removed a lingering test logcat printout.
=> fix: Remove test log

src/android/FileUtils.java
Android
As this fine gentlemen pointed out [here](https://github.com/apache/cordova-plugin-file/commit/1a430505437951f635e403bf9e9257cbc6f8e8f7#r56007026), I messed up in PR #470 and accidentally removed the `return` statement that was at the end of the line.
=> fix: Brought back the return statement -- also corrected code formatting

tests/plugin.xml, tests/tests.js
Cordova Contact Plugin has been deprecated and should be removed.
* Removed dependency
* Removed test releated code.
n/a
=> test: remove deprecated cordova-plugin-contact tests

README.md, plugin.xml, src/android/FileUtils.java
Android
Progresses https://github.com/apache/cordova-plugin-file/issues/426 but unsure if it completely resolves it
Code changes includes checking to see the file path on reading directory listings (for listing directories and files) and if the file path happens to be an "external" file path, then assert/request READ_EXTERNAL_STORAGE permission.
There have been a couple of documentation changes as well, including the fact that some directories that were previously writable in earlier API versions are no longer writable starting in API 30.
`requestLegacyExternalStorage` flag is removed because that was an API 29 only flag. This flag is not honoured on API 30 and is forcefully false.
Npm test and manual testing using a test app: https://github.com/breautek/cordova-file-api30-test-app
I'm …
=> feat: Request external permission when listing external directories

plugin.xml, www/Entry.js, www/android/Entry.js
all
Recent changes to toURL should only be applied to Android
Created an Android only override and reverted original code.
- cordova build
- run tests
=> fix(android): create toURL override to preserve other platforms

src/android/FileUtils.java, tests/tests.js
android
`cdvfile://` protocol is no longer supported and the assets file system was not working with recent changes to support the new cdvfile url pattern. 
This PR is to support the assets file sytem
Updated the `WebViewAssetLoader.PathHandler` to include `assets`
E.g. `https://localhost/__cdvfile_assets__/` will map to app's assets `/android_asset/`
- cordova build
- cordova run
- test specs
=> fix(android): support cdvfile assets for custom scheme

.eslintrc.yml, tests/tests.js
android
tests failing with Cordova-Android 10.x because default scheme has changed to `https`.
Update the test's default scheme to `https` for android.
- test specs
=> test(android): fix tests to use cordova-android 10.x default https scheme

.eslintrc.yml, tests/tests.js, www/Entry.js, www/FileReader.js, www/FileWriter.js, www/android/Entry.js, www/android/FileSystem.js, www/browser/FileSystem.js, www/browser/Preparing.js, www/requestFileSystem.js, www/resolveLocalFileSystemURI.js
windows8, windowsphone, blackberry, amazon-fireos
The above platforms has been deprecated and no longer supported for a long time.
This PR removed the residual old platform code & also applied lint corrections.
- not available as the old platform core code was not exisiting.
=> chore!: removed old platform code & lint cleanup

types/index.d.ts
FileWriter.js clearly supports this type, and it allows memory conscious users to avoid unnecessary duplication of the memory as occurs when using a Blob.
Type-only change
Avoid forcing unnecessary duplication of memory when attempting to write files
Clarifies `FileWriter.write` type definition to properly reflect the method's support for an `ArrayBuffer` type directly: https://github.com/apache/cordova-plugin-file/blob/c883998c011fd5b26a1643b6c65de0c6f6ed21e7/www/FileWriter.js#L156
Type-only change. Have confirmed new type behaves correctly with code passing in an ArrayBuffer.
=> fix(types): Mark FileWriter.write to support ArrayBuffer data

tests/tests.js
n/a
Update Android test spec to follow testing environment setup.
* Check for http, not https, as app is running with http scheme.
GitHub Action
=> spec(android): fix spec based on testing environment

README.md, plugin.xml
Android
`WRITE_EXTERNAL_STORAGE` permission brings build error at Android SDK 33.
closes #543
closes https://github.com/apache/cordova-plugin-file/issues/243
Remove `WRITE_EXTERNAL_STORAGE` from `plugin.xml`.
Exec Local test with cordova-paramedic.
All tests passed with Pixel 5 API 30 and Pixel 5 API 33.
=> feat: remove WRITE_EXTERNAL_STORAGE permission from plugin.xml

src/android/FileUtils.java
**Refer to :** https://developer.android.com/about/versions/13/behavior-changes-13
=> feat(android): add READ_MEDIA_* permissions for Android 13+

src/android/ContentFilesystem.java
Android
This solves issue https://github.com/apache/cordova-plugin-file/issues/525 which is a serious problem.
Closes apache/cordova-plugin-file#525
This implements the fix described in https://github.com/apache/cordova-plugin-file/issues/525#issue-1265882820
I tested locally, pushed to production. Approximately 1000 installs working with no issues.
=> fix(android): FileError on a content resolveLocalFileSystemURL

src/android/AssetFilesystem.java, src/android/ContentFilesystem.java, src/android/FileUtils.java, src/android/Filesystem.java, src/android/LocalFilesystem.java, src/android/LocalFilesystemURL.java
android
Cleanup code and follow standards
- Corrected indention levels with Android Studio
- Replaced mixing of tab indentions with spaces (VSCode)
-  Import Optimization with Android Studio
- Removed a double caught exception.
- Removed unused `permissions` global array variable
- Move part of the `permissions` comment to `hasReadPermission`
- Removed Trailing Spaces
For eaiser review, try enabling the `Hide whitespace` setting.
- `cordova plugin add ...`
- `cordova build android`
- `npm t`
=> refactor(android): various cleanup

src/android/FileUtils.java
android
rebase, fix, and simplify changes from #581
Closes #581
This PR performed following changes against #581:
- Rebased against current main branch
- Reverted previous changes to `getWritePermission` but applied suggestion to simplify. the condition check and to add extra accidental calls, even though the method would never be called in that scenario.
-  Simplifed `hasWritePermission` logic
- Added comment suggestion to `hasWritePermission`
`build test`
=> fix(android): hasWritePermission for SDK 33

README.md, plugin.xml, src/ios/CDVFile.bundle/PrivacyInfo.xcprivacy
ios
Support Apple's Privacy Manifest requirements
closes https://github.com/apache/cordova-plugin-file/issues/620
- Created a resource bundle
- Added `PrivacyInfo.xcprivacy` to the resource bundle
- Load bundle into iOS project with `resource-file` in `plugin.xml`
The bundle is prefixed with Cordova's internal `CDV` namespace. 
Note for third-party plugins: When creating a bundle or even class names, it is recommended to establish your own namespace and utilize a unique identifier to prevent conflicts with other plugins.
- platform add
- plugin add
- archive project
- generated privacy report
=> feat(ios): add bundled resources for privacy manifest

src/android/FileUtils.java
Android
Improves support for the webview asset loader Path handling for easier DOM access,
especially for `content://` urls.
There are 3 main changes:
1. Assets filesystem check is unsafe
`targetFileSystem == "assets";`
does not do what might have been expected, the condition will always yield false.
This is because in Java, comparing an object to a string literal using a `==` operator is a reference equality check. That is it's not testing if the values are equal, it's testing if they are the *same* object. Because a string literal is always making a new object to evaluate this line, it will always be false.
This was corrected to use `.equals` which does a value equality check.
2. Support `content` filesystem.
The existing path handler supported many different filesystems, but `content` …
=> fix(android): Content FS support in PathHandler

README.md
=> Update specs in readme

README.md
1. The `onwriteend` samples are wrong. The correct callback is `onwrite` for sucessful writes, as you can see here:
https://github.com/apache/cordova-plugin-file/blob/92caa81b724019b9cc63fba7a0838b69ea6312d2/www/FileWriter.js#L62-L63
https://github.com/apache/cordova-plugin-file/blob/92caa81b724019b9cc63fba7a0838b69ea6312d2/www/FileWriter.js#L65-L66
2. Corrected console.log-messages in `onwrite` and `onerror`, where it mistakenly says "Successful file **read**..." instead of "**write**"
=> README.md: Correct onwriteend to onwrite

src/android/FileUtils.java
Android
Regression from https://github.com/apache/cordova-plugin-file/commit/99ca43990c0bcdf19645367a27f1f8106d1be71d
Code strips out the `file://` protocol for what used to be used by File APIs, but in 8.1.1 that was changed to use CordvaResourceApi which expects an actual valid URI.
If the uri object has no scheme set, then set it to the `file` scheme.
paramedic tests passes.
Testing by using camera plugin to capture an image, resolve the `file://` uri and attempt to set an image tag `src` attribute to the `fileEntry.toURL()` result.
=> fix(android): Regression breaking resolved DOM-usable file:// paths

plugin.xml, tests/tests.js, www/ios/Entry.js
iOS
Entry's `toURL()` method is intended to produce a DOM-usable URIs.
This works as intended on Android.
On iOS however, it only worked if the app was configured to be in a `file://` hosted webview. If the webview was configured to use schemes, it would still produce a `file://` uri which is not usable in the DOM.
I believe this can be considered a patch, for `file://` hosted users, this should behave the same as before. For scheme-hosted users, the `.toURL()` will return a different URI, but the original format didn't work as intended. If the user were using `.toURL()` for another purpose, then this could be considered a breaking change?
Mimick how Android solves this issue, by creating an ios specific `Entry.js` file which contains a `toURL` method override with iOS specific logic. …
=> fix(ios): Entry.toURL() to produce DOM-usable uri when using scheme-hosted webview

tests/tests.js
tests
On iOS (and I think any file api I've ever used), reading directories does not define any particular order of files. The iOS implementation uses [contentsOfDirectoryAtPath:error:](https://developer.apple.com/documentation/foundation/nsfilemanager/1414584-contentsofdirectoryatpath) which states:
> The order of the files in the returned array is undefined.
While this test does not appear to be failing actively on GH actions, it was failing for me locally due to the expectation assuming that they will be in a particular order.
Reworked the test so that it will scan for each expected value and keep track which ones it has found.
Assertions of the expected item count remains.
Asserts that each item is found.
Ran mobilespec locally on iOS.
=> fix(test): file.spec.131 moveTo may fail due to read order assumption
