apache/cordova-plugin-file

- src/wp/File.cs
This solves: https://issues.apache.org/jira/browse/CB-7927
> [CB-7927] Encoding data to bytes instead of chars when writing a file.

- src/wp/File.cs
Implemented some missing functions in WP8
> Binary readers wp8

- doc/index.md
- plugin.xml
- src/browser/FileProxy.js
- tests/tests.js
- www/Entry.js
- www/browser/FileSystem.js
- www/browser/Preparing.js
- www/requestFileSystem.js
- www/resolveLocalFileSystemURI.js
* Added Firefox and IE support via IndexedDB
* Updated the docs
* Updated the tests
> CB-7956 Add cordova-plugin-file support for browser platform

- www/FileReader.js
https://issues.apache.org/jira/browse/CB-8849
> CB-8849 Fixed ReadAsArrayBuffer to return ArrayBuffer and not Array on WP8

- tests/tests.js
[Jira issue](https://issues.apache.org/jira/browse/CB-9215)
> CB-9215 Add cordova-plugin-file manual test for windows platform

- tests/plugin.xml
- tests/tests.js
- tests/www/fixtures/asset-test/asset-test.txt
https://issues.apache.org/jira/browse/CB-9539
> CB-9539 Fixed test failure on Android emulator

- .gitignore
- www/resolveLocalFileSystemURI.js
fix resolveLocalFileSystemURI.js to export webkitResolveLocalFileSystemURL as resolveLocalFileSystemURL definition for browser platform
> Override resolveLocalFileSystemURL by webkitResolveLocalFileSystemURL

- src/ios/CDVFile.m
Close #125 Close #138
Fixes iOS native only implementation. And clean up PRs
> CB-9331 getFreeDiskSpace iOS. 

- plugin.xml
- src/android/FileUtils.java
- src/android/PermissionHelper.java
As discussed on the mailing list. I ran the manual and auto mobilespec tests with cordova-android's master and cordova-android 3.7.2 and both seemed to match the output of vanilla mobilespec. @infil00p @jasongin please review.
> CB-10319 android: Adding reflective helper methods for permission requests

- tests/tests.js
Check if external storage is available
[Jira issue](https://issues.apache.org/jira/browse/CB-10411)
> CB-10411 Error in file.spec.129 of cordova-plugin-file

- .gitignore
- .jshintrc
- .travis.yml
- README.md
- package.json
- src/blackberry10/index.js
- src/browser/FileProxy.js
- src/firefoxos/FileProxy.js
- src/windows/FileProxy.js
- tests/tests.js
- www/Entry.js
- www/FileEntry.js
- www/FileReader.js
- www/FileSystem.js
- www/blackberry10/.jshintrc
- www/blackberry10/FileSystem.js
- www/blackberry10/copyTo.js
- www/blackberry10/readEntries.js
- www/blackberry10/requestAllFileSystems.js
- www/blackberry10/truncate.js
- www/blackberry10/write.js
- www/browser/Preparing.js
- www/fileSystems-roots.js
- www/requestFileSystem.js
- www/resolveLocalFileSystemURI.js
- www/ubuntu/FileWriter.js
- www/ubuntu/fileSystems-roots.js
[Jira issue](https://issues.apache.org/jira/browse/CB-10636)
Fixed file.spec.115
> CB-10636 Add JSHint for plugins

- www/FileWriter.js
[Jira issue](https://issues.apache.org/jira/browse/CB-10960)
> CB-10960 Uncaught #<FileError> in write() when readyState != WRITING ?

- README.md
In function writeFile changed console.log("Successful file read") to console.log("Successful file write")
> Fixed Multiple console log issues

- package.json
> CB-13518  (all): Add 'protective' entry to cordovaDependencies

- .travis.yml
> CB-13753: Add build-tools-26.0.2 to travis

- package-lock.json
none
use latest npm package-lock.json version & fix audit warnined
rebuilt package-lock
n/a
> chore(npm): bump package-lock.json to v2

- .github/workflows/android.yml
- .github/workflows/chrome.yml
- .github/workflows/ios.yml
- .github/workflows/lint.yml
Sync GitHub Workflow with Paramedic base configs.
n/a
> ci: sync github workflow with paramedic base configs

- package-lock.json
- package.json
- plugin.xml
- tests/package.json
- tests/plugin.xml
n/a
bumping for minor changes
bump package version to 8.1.0-dev
n/a
> chore: bump version 8.1.0-dev

- .github/workflows/android.yml
- .github/workflows/chrome.yml
- .github/workflows/ios.yml
- .github/workflows/lint.yml
n/a
Update CI Workflow
Updated:
- Dependencies
- Android test matrix
- iOS test matrix
- Use linux & enable KVM
- Use node 20
n/a
> ci: sync workflow with paramedic

- package-lock.json
n/a
- Rebuilt package-lock.json with v3.
- Resolves audit for dev
n/a
> chore: rebuilt package-lock.json w/ version 3
